### ISSUE TITLE
Callback invocation count

### ISSUE THREAD

**Issue by LordRaydenMK** [qonversion/android-sdk#276] opened 2021-12-21 08:59 UTC
We use Qonversion in an app where we also use Kotlinx Coroutines, so we wrapped the SDK methods into suspend functions e.g.

```
suspend fun Qonversion.awaitProducts(): Map<String, QProduct> = suspendCoroutine { cont ->
    products(object : QonversionProductsCallback {

        override fun onError(error: QonversionError) {
            cont.resumeWithException(QonversionException(error)) // custom class, extends Throwable
        }

        override fun onSuccess(products: Map<String, QProduct>) {
            cont.resume(products)
        }

    })
}
```

I noticed a `IllegalStateException Already resumed` on Sentry related to this (or similar code - not sure exactly which call it is). It means the callback is firing twice or more. That would mean that for that specific call the fix is to use a `Flow` instead of a suspend function in my wrapper code.

Is is documented somewhere how many times it's expected for the callbacks to be executed?

Thanks.

**Comment by SpertsyanKM** [comment] 2021-12-21 09:40
Hello! Thank you for contacting us! I'll try to help you.

I've checked the `products` method and it does call callback methods exactly once (either onSuccess or onError). It would be great if you could find and provide the concrete method, which causes you this error.

Each callback passed to Qonversion should be called once, except `UpdatedPurchasesListener`. If it's not so then there is a bug.

**Comment by LordRaydenMK** [comment] 2021-12-21 09:53
Thanks for the quick reply.

> Each callback passed to Qonversion should be called once, except UpdatedPurchasesListener. If it's not so then there is a bug.

☝️ exactly the information I needed.

In our app we have wrappers for: `QonversionPermissionsCallback`, `QonversionOfferingsCallback`, `QonversionProductsCallback` and `QonversionPermissionsCallback` used with the methods: `restore`, `offerings`, `products`, `purchase` and `restore`. Unfortunately Sentry doesn't do a great job de-obfuscating the stack trace so at the moment I don't have the exact one. Also the crash only happened once so might be some edge case.

We are using version: 3.1.2 of the SDK.

**Comment by SpertsyanKM** [comment] 2021-12-21 09:57
Okay, thank you for the provided information! We will check these methods to find out some mistakes. I will write you back as soon as we complete that research.

**Comment by SpertsyanKM** [comment] 2021-12-22 07:53
I've checked all of these methods and they all invoke the given callback just once. Please, make sure the problem is not with `UpdatedPurchasesListener` as it is the only listener called multiple times and thus cannot be replaced with `suspendCoroutine`.

By the way, we've got good news for you - right now we are working on the new version of SDK backed with coroutines, so after it Is released you won't need your own wrappers. We can't name a concrete release date right now but it will be ready in several months. So keep for updates.

I'm closing this issue but feel free to reopen it if any new info will appear.

**Closed by SpertsyanKM** 2021-12-22 07:53 UTC
