### ISSUE TITLE
Twice calling continuation.resume in suspend function

### ISSUE THREAD

**Issue by enister** [qonversion/android-sdk#342] opened 2022-05-04 14:30 UTC
Hello!

We use `suspendCancellableCoroutine` inside the method `Qonversion.checkTrialIntroEligibilityForProductIds`. And we have got many crashes about twice calling `continuation.resume`. I checked the [issue](https://github.com/qonversion/android-sdk/issues/276) with the similar problem and i understand that it's a bug.

Code (com.example.app.Code.kt):
```
1    suspendCancellableCoroutine { continuation ->
2        Qonversion.checkTrialIntroEligibilityForProductIds(
3            listOf("main", "secondary"),
4            object : QonversionEligibilityCallback {
5
6               override fun onSuccess(eligibilities: Map<String, QEligibility>) {
7                   continuation.resume(eligibilities)
8               }
9
10              override fun onError(error: QonversionError) {
11                   handleError(continuation, error)
12              }
13
14            }
15       )
16    }
```

Crash
```
Fatal Exception: java.lang.IllegalStateException: Already resumed, but proposed with update [some data]
       at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:482)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:447)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
       at com.example.app.Code.kt:7
       at com.qonversion.android.sdk.Qonversion$checkTrialIntroEligibilityForProductIds$1.onSuccess(Qonversion.kt:297)
       at com.qonversion.android.sdk.QProductCenterManager$checkTrialIntroEligibilityForProductIds$1$onSuccess$1.onSuccess(QProductCenterManager.kt:232)
       at com.qonversion.android.sdk.QonversionRepository$eligibilityForProductIds$1$1.invoke(QonversionRepository.kt:152)
       at com.qonversion.android.sdk.QonversionRepository$eligibilityForProductIds$1$1.invoke(QonversionRepository.kt:44)
       at com.qonversion.android.sdk.CallBackKt.onResponse(extensions.kt:23)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda1.run(:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7766)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

How can it be fixed?

Unfortunately, the steps for reproducing the crash was not found by me.

Thanks in advance

**Comment by SpertsyanKM** [comment] 2022-05-06 16:28
Hello! Thank you for your report! 

We were also unable to reproduce it but we have reviewed all the flow again and found several places that may cause such behavior. The fix is already released in versions 3.2.7 and 2.11.9 (will be available in a few minutes). Please, try it out and tell us if it helped or not.

**Closed** 2022-05-18 11:26 UTC
