### ISSUE TITLE
build version - problem

### ISSUE THREAD

**Issue by dmitriev-alexey** [qonversion/android-sdk#443] opened 2023-01-23 13:01 UTC
Greetings.
In the new version SDK I have a problem with app version.
Please check my screenshots(in attach) for more details.
[old version ](https://ibb.co/2K01Nnv)
[new version 4.1.0 ](https://ibb.co/QfWKrdr)

**Comment by suriksarkisyan** [comment] 2023-01-24 15:43
Hi, @dmitriev-alexey 
I found the problem. The fix will be released soon! Thank you for the help! 🤝

**Comment by suriksarkisyan** [comment] 2023-01-25 14:37
Hi again, @dmitriev-alexey 
Happy to say that [4.1.2](https://github.com/qonversion/android-sdk/releases/tag/4.1.2) has been published. Could you please update the SDK and check that the problem is gone?

**Closed** 2023-02-08 02:04 UTC
Labels: awaiting answers
